# By default the `default` profile will be used.
# Here you are able to override this.
default_profile = "default"

# The default profile is used when no arguments are provided,
# or as a base for other profiles.
[profile.default]
username = ""
password = ""

awsRegion = ""
awsUserPool = ""
awsClientId = ""

# Define a custom profile which can be referenced with `--profile <name>`
[profile.my_profile]
username = ""
password = ""

awsRegion = ""
awsUserPool = ""
awsClientId = ""

# You can define a partial profile as long as the remaining
# fields will be covered by the `default` profile.
[profile.my_partial]
username = ""
